config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :loans
  resources :sales
  resources :employees
  resources :users
  resources :cars
  resources :customers
  root to: "cars#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord

  def self.search(search)
    if search
      where('name LIKE ? OR last_name LIKE ? OR role LIKE ? OR email LIKE ? OR phone LIKE ? OR address LIKE ?', "%#{search}%",  "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      all
    end
  end


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /employees
  # GET /employees.json
  def index
    authorize! :index, @employee
    @employees = Employee.all.paginate(:per_page => 20, :page => params[:page]).search(params[:search])
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    authorize! :show, @employee
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
    authorize! :edit, @employee
  end

  # POST /employees
  # POST /employees.json
  def create
    authorize! :create, @employee
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    authorize! :update, @employee
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    authorize! :destroy, @employee
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :last_name, :email, :address, :phone, :role)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name,class: 'form-control'  %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name,class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email,class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :address %>
    <%= form.text_field :address,class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone,class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :role %>
    <%= form.text_field :role ,class: 'form-control' %>
  </div>

  <div class="actions" id="buttonright">

    <%= form.submit:class => 'btn btn-dark'  %>

  </div>



<% end %>

app/views/employees/edit.html.erb
<p id="notice"><%= notice %></p>



<div class="container-fluid">


  <!-- web application title -->
  <div class="col-xs-12 text-center">

    <div id="cartest"></div>
    <p id="apptitle">Hou-Tex Auto Dealership</p>


  </div>



  <!--NEW navigation bar made using css instead of bootstrap-->


  <div class="topnav" id="myTopnav">

    <a href="/cars" c>CARS</a>

    <a href="/employees">EMPLOYEES</a>

    <a href="/sales">SALES</a>

    <a href="/customers">CUSTOMERS</a>

    <a href="/loans">LOANS</a>

    <a href="/users">USERS</a>

  </div>



  <!-- page title -->


  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <p id="title">Employees</p>
    </div>
    <div class="col-md-8">

    </div>
  </div>




  <!-- middle row page section -->
  <!-- form section -->
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">

      <div id="carform">
        <p id="formtitle">Edit Employee</p>


        <%= render 'form', employee: @employee %>

        <div id="backbutton">
          <%= link_to 'Show', @employee,class: 'btn btn-dark'  %>  |
          <%= link_to 'Back', employees_path,class: 'btn btn-dark'  %>
        </div>

      </div>





    </div>





  </div>
  <div class="col-md-2">

  </div>
</div>


<br>



</div>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">

  <!-- web application title -->
  <div class="col-xs-12 text-center">
    <p id="apptitle">Hou-Tex Auto Dealership</p>
  </div>
</div>

<!--NEW navigation bar made using css instead of bootstrap-->


<div class="topnav" id="myTopnav">

  <a href="/cars" c>CARS</a>

  <a href="/employees">EMPLOYEES</a>

  <a href="/sales">SALES</a>

  <a href="/customers">CUSTOMERS</a>

  <a href="/loans">LOANS</a>

  <a href="/users">USERS</a>

</div>



<!-- page title -->


<div class="row">
  <div class="col-md-2">

  </div>
  <div class="col-md-8">
    <p id="title">Employees</p>
  </div>
  <div class="col-md-2">

  </div>
</div>






<!-- area above table -->
<div class="row">
  <div class="col-md-2">

  </div>
  <div class="col-md-8">

    <div id="createemp">



      <% if can? :create, @employee %>
        <%= link_to 'New Employee', new_employee_path, class: 'btn btn-dark' %>
      <%end%>


    </div>

    <div id="searchemp">
    <%= form_tag employees_path, :method => 'get', :id => "employees_search" do %>

        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil , class: 'btn btn-dark'%>

    <% end %>
    </div>

  </div>
  <div class="col-md-2">

  </div>
</div>

<!-- table -->
<div class="row">
  <div class="col-md-2">

  </div>
  <div class="col-md-8">
    <table class="table table-bordered table-hover table-dark" id="cartable" >
      <thead>
      <tr>
        <th scope="col"  width="230px" >First Name</th>
        <th scope="col"  width="230px" >Last Name</th>
        <th scope="col"  width="230px" >Email</th>
        <th scope="col"  width="230px" >Address</th>
        <th scope="col"  width="230px">Phone Number</th>
        <th scope="col"  width="230px">Role</th>
        <th colspan="3">Update Record</th>
      </tr>
      </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.address %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.role %></td>
        <% if can? :read, @employee %>
        <td><%= link_to 'Show', employee %></td>
          <%end%>
        <% if can? :update, @employee %>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
          <%end%>
        <% if can? :destroy, @employee %>
        <td><%= link_to 'Remove', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

  </div>
  <div class="col-md-2">

  </div>
</div>


</div>

app/views/employees/new.html.erb
<p id="notice"><%= notice %></p>



<div class="container-fluid">


  <!-- web application title -->
  <div class="col-xs-12 text-center">

    <div id="cartest"></div>
    <p id="apptitle">Hou-Tex Auto Dealership</p>


  </div>



  <!--NEW navigation bar made using css instead of bootstrap-->


  <div class="topnav" id="myTopnav">

    <a href="/cars" c>CARS</a>

    <a href="/employees">EMPLOYEES</a>

    <a href="/sales">SALES</a>

    <a href="/customers">CUSTOMERS</a>

    <a href="/loans">LOANS</a>

    <a href="/users">USERS</a>

  </div>



  <!-- page title -->


  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <p id="title">Employees</p>
    </div>
    <div class="col-md-8">

    </div>
  </div>




  <!-- middle row page section -->
  <!-- form section -->
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <div id="carform">
        <h1>New Employee</h1>


        <%= render 'form', employee: @employee %>

        <div id="backbutton">

          <%= link_to 'Back', employees_path,class: 'btn btn-dark' %>
        </div>

      </div>






    </div>





  </div>
  <div class="col-md-2">

  </div>
</div>


<br>



</div>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>



<div class="container-fluid">


  <!-- web application title -->
  <div class="col-xs-12 text-center">

    <div id="cartest"></div>
    <p id="apptitle">Hou-Tex Auto Dealership</p>


  </div>



  <!--NEW navigation bar made using css instead of bootstrap-->


  <div class="topnav" id="myTopnav">

    <a href="/cars" c>CARS</a>

    <a href="/employees">EMPLOYEES</a>

    <a href="/sales">SALES</a>

    <a href="/customers">CUSTOMERS</a>

    <a href="/loans">LOANS</a>

    <a href="/users">USERS</a>

  </div>



  <!-- page title -->


  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <p id="title">Employees</p>
    </div>
    <div class="col-md-8">

    </div>
  </div>




  <!-- middle row page section -->
  <!-- form section -->
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">

      <div id="empform">
        <p id="formtitle">New Employee Created</p>

        <p>
          <strong>Name:</strong>
          <%= @employee.name %>
          <br/>



        </p>

        <p>
          <strong>Last name:</strong>
          <%= @employee.last_name %>
          <br/>

        </p>

        <p>
          <strong>Email:</strong>
          <%= @employee.email %>
          <br/>

        </p>

        <p>
          <strong>Address:</strong>
          <%= @employee.address %>
          <br/>

        </p>

        <p>
          <strong>Phone:</strong>
          <%= @employee.phone %>
          <br/>

        </p>

        <p>
          <strong>Role:</strong>
          <%= @employee.role %>
        </p>

        <% if can? :update, @employee %>


        <div id="backne">
          <%= link_to 'Back', employees_path,class: 'btn btn-dark' %>
        </div>
        <div id="editne">
          <%= link_to 'Edit', edit_employee_path(@employee),class: 'btn btn-dark' %>
        </div>

        <%end%>



      </div>





    </div>





  </div>
  <div class="col-md-2">

  </div>
</div>


<br>



</div>