config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :loans
  resources :sales
  resources :employees
  resources :users
  resources :cars
  resources :customers
  root to: "cars#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/loan.rb
class Loan < ApplicationRecord

  attr_accessor :calculation

  def amortization
    @calculation  = Hash.new
    @calculation[:payments] = Array.new(periods)
    @calculation[:total] = (payment(principal, interest_rate, payment_type, periods).round(2))
    @calculation[:periods] = Array.new(periods)
    @calculation[:principals] = Array.new(periods)
    @calculation[:interests] = Array.new(periods)
    @calculation[:balances] = Array.new(periods)

    #Initial conditions
    @calculation[:payments][0] = 0
    @calculation[:principals][0] = 0
    @calculation[:interests][0] = 0
    @calculation[:balances][0] = principal

    #Inserting data into Arrays
    for i in (1..periods)
      if i != periods
        @calculation[:payments][i] = payment(principal, interest_rate, payment_type, periods)
      else
        @calculation[:payments][i] = payment(principal, interest_rate, payment_type, periods)
      end
      @calculation[:interests][i] = ((@calculation[:balances][i-1]).to_f * (interest_rate/payment_type_yearly_frecuency(payment_type))).round(2)
      @calculation[:principals][i] = (@calculation[:payments][i] - @calculation[:interests][i]).round(2)
      if i == periods
        @calculation[:balances][i] = (@calculation[:balances][i-1] - @calculation[:payments][i] + @calculation[:interests][i]).round(0)
      else
        @calculation[:balances][i] = (@calculation[:balances][i-1] - @calculation[:payments][i] + @calculation[:interests][i]).round(2)
      end

    end

    # def payment_type_yearly_frequency(payment_type)
    #   case payment_type
    #   when 1 then 12
    #   when 2 then 24
    #   when 3 then 26
    #   when 4 then 54
    #   else 12
    #   end
    # end

    # # Return fixed payment during all loan
    # def payment(principal, interest_rate, payment_type, periods)
    #   (principal * ( (interest_rate/payment_type_yearly_frecuency(payment_type)/(1-((1+interest_rate/payment_type_yearly_frecuency(payment_type))**(periods * -1)))) )).round(2)
    # end

  end

  def payment(principal, interest_rate, payment_type, periods)
    (principal * ( (interest_rate/payment_type_yearly_frecuency(payment_type)/(1-((1+interest_rate/payment_type_yearly_frecuency(payment_type))**(periods * -1)))) )).round(2)
  end

  def payment_type_yearly_frecuency(payment_type)
    case payment_type
    when 1 then 12
    when 2 then 24
    when 3 then 26
    when 4 then 54
    else 12
    end
  end


  # def add (principal, interest_rate, periods, payment_type)
  #   puts  " values ---------"
  #   puts  principal
  #   puts interest_rate
  #   puts  "---------"
  #   @total = principal + periods + interest_rate + payment_type
  # end

  # def payment(periods)
  #   payments = []
  #   for periods in 1..periods do
  #     payments.push(periods)
  #   end
  #   payments
  #
  #  #  for 12 months  do
  #  #     payment =(principal * ( (interest_rate/12/(1-((1+interest_rate/12)**(periods * -1)))) )).round(2)
  #  #  payments.push(payment)
  #  #  end
  #  #  payments
  # end

  # def payment(principal, interest_rate, periods)
  #   months = periods * 12
  #   payment = []
  #   for months in 1..months do
  #     payment.push(months)
  #     # payments = (principal * ( (interest_rate/(periods)/(1-((1+interest_rate/(periods))**(periods * -1)))) )).round(2)
  #     # payment.push(payments)
  #   end
  #   payment
  # end



end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /loans
  # GET /loans.json
  def index
    authorize! :index, @loan
    @loans = Loan.all
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
    authorize! :show, @loan
    @loan.amortization
    #puts @loan
    respond_to do |format|
      format.html
      format.pdf do

        pdf = LoanPdf.new(@loans)
        send_data pdf.render, filename: "Loan.pdf", type: "application/pdf", dispostion: "inline"


        # authorize! :index, @sale
        # @sales = Sale.all
        # #puts @sales
        # respond_to do |format|
        #   format.html
        #   format.pdf do
        #
        #     pdf = SalePdf.new(@sales)
        #     send_data pdf.render, filename: "Sales.pdf", type: "application/pdf",disposition: "inline"

      end
    end
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:principal, :interest_rate, :periods, :payment_type)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_amortization_schedule.html.erb
<h1>Amortization Schedule</h1>
<table class = "table table-hover">
  <thead>

    <tr>
      <td>Period</td>
      <td>Payment</td>
      <td>Principal</td>
      <td>Interest</td>
      <td>Loan Balance</td>
    </tr>

  </thead>

  <tbody>
    <% for i in (1..@loan.periods) %>
      <tr>
        <td><%= i %></td>
        <td><%= @loan.calculation[:payments][i] %></td>
        <td><%= @loan.calculation[:principals][i] %></td>
        <td><%= @loan.calculation[:interests][i] %></td>
        <td><%= @loan.calculation[:balances][i] %></td>
      </tr>
    <%end %>

  </tbody>

</table>

<p></p>

<div class="container">

  <%#= render 'loan_information' %>

  <br>

  <p id="notice"><%=notice%></p>
</div>

app/views/loans/_form.html.erb
<%= form_with(model: loan, local: true) do |form| %>
  <% if loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :principal %>
    <%= form.text_field :principal %>
  </div>

  <div class="field">
    <%= form.label :interest_rate %>
    <%= form.text_field :interest_rate %>
  </div>

  <div class="field">
    <%= form.label :periods %>
    <%= form.number_field :periods %>
  </div>

  <div class="field">
    <%= form.label :payment_type %>
    <%= form.number_field :payment_type %>
  </div>

  <div class="actions" id="buttonright">
    <%= form.submit:class => 'btn btn-dark'  %>
  </div>


<% end %>

app/views/loans/edit.html.erb
<div class="container-fluid">


  <!-- web application title -->
  <div class="col-xs-12 text-center">


    <p id="apptitle">Hou-Tex Auto Dealership</p>


  </div>



  <!--NEW navigation bar made using css instead of bootstrap-->


  <div class="topnav" id="myTopnav">

    <a href="/cars">CARS</a>

    <a href="/employees">EMPLOYEES</a>

    <a href="/sales">SALES</a>

    <a href="/customers">CUSTOMERS</a>

    <a href="/loans">LOANS</a>

    <a href="/users">USERS</a>

  </div>



  <!-- page title -->


  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <p id="title">Loans</p>
    </div>
    <div class="col-md-8">

    </div>
  </div>




  <!-- middle row page section -->
  <!-- form section -->
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">

      <div id="loancreatedform">
        <p id="formtitle">Edit Loan</p>

        <%= render 'form', loan: @loan %>

        <div id="backbutton">
          <%= link_to 'Show', @loan ,class: 'btn btn-dark'%> |
          <%= link_to 'Back', loans_path,class: 'btn btn-dark' %>

        </div>
      </div>





    </div>





  </div>
  <div class="col-md-2">

  </div>
</div>


<br>



</div>

app/views/loans/index.html.erb
<!-- LOANS main page -->
<p id="notice"><%= notice %></p>



<div class="container-fluid">


  <!-- web application title -->
  <div class="col-xs-12 text-center">

    <div id="cartest"></div>
    <p id="apptitle">Hou-Tex Auto Dealership</p>


  </div>

  <!--NEW navigation bar made using css instead of bootstrap-->


  <div class="topnav" id="myTopnav">

    <a href="/cars">CARS</a>

    <a href="/employees">EMPLOYEES</a>

    <a href="/sales">SALES</a>

    <a href="/customers">CUSTOMERS</a>

    <a href="/loans">LOANS</a>

    <a href="/users">USERS</a>

  </div>



  <!-- page title -->


  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <p id="title">Loans</p>

    </div>
<br>
    <div class="col-md-8">

    </div>
  </div>

  <!-- car button and search bar -->

  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <div id="rightsearch">

        <%#= form_tag loans_path, :method => 'get', :id => "loans_search" do %>
<!--          <p>-->
            <%#= text_field_tag :search, params[:search] %>
            <%#= submit_tag "Search", :name => nil ,class: 'btn btn-dark'%>
<!--          </p>-->
        <%# end %>


      </div>
      <div id="leftindex">

        <% if can? :create, @loan %>
          <%= link_to 'New Loan', new_loan_path,class: 'btn btn-dark' %>

        <%end%>
      </div>

    </div>
    <div class="col-md-2">

    </div>
  </div>


  <!-- table -->

  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">

      <table class="table table-bordered table-hover table-dark" id="cartable" >
        <thead>
        <tr>
          <th scope="col"  width="230px" >Principal</th>
          <th scope="col"  width="230px" >Interest Rate</th>
          <th scope="col"  width="230px" >Periods</th>
          <th scope="col"  width="230px">Payment Type</th>
          <th colspan="3">Update Record</th>
        </tr>
        </thead>

        <tbody>
        <% @loans.each do |loan| %>
          <tr>
            <td><%= loan.principal %></td>
            <td><%= loan.interest_rate %></td>
            <td><%= loan.periods %></td>
            <td><%= loan.payment_type %></td>
            <td><%= link_to 'Show', loan %></td>
            <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
            <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>

          </tr>
        <% end %>
        </tbody>


      </table>


    </div>
    <div class="col-md-2">

    </div>
  </div>







  <br>



</div>

app/views/loans/new.html.erb
<!-- new  loan page -->


<div class="container-fluid">


  <!-- web application title -->
  <div class="col-xs-12 text-center">

    <div id="cartest"></div>
    <p id="apptitle">Hou-Tex Auto Dealership</p>


  </div>

  <!--NEW navigation bar made using css instead of bootstrap-->


  <div class="topnav" id="myTopnav">

    <a href="/cars" >CARS</a>

    <a href="/employees">EMPLOYEES</a>

    <a href="/sales">SALES</a>

    <a href="/customers">CUSTOMERS</a>

    <a href="/loans">LOANS</a>

    <a href="/users">USERS</a>

  </div>



  <!-- page title -->


  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <p id="title">Loans</p>
    </div>
    <div class="col-md-8">

    </div>
  </div>



  <!-- middle row -->

  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">

      <div id="loanform">
        <p id="formtitle">New Loan</p>

        <%= render 'form', loan: @loan %>

        <div id="backnl">
        <%= link_to 'Back', loans_path,class:'btn btn-dark' %>
        </div>

      </div>


    </div>
    <div class="col-md-2">

    </div>
  </div>





  <br>



</div>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">


  <!-- web application title -->
  <div class="col-xs-12 text-center">

    <div id="cartest"></div>
    <p id="apptitle">Hou-Tex Auto Dealership</p>


  </div>



  <!--NEW navigation bar made using css instead of bootstrap-->


  <div class="topnav" id="myTopnav">

    <a href="/cars" >CARS</a>

    <a href="/employees">EMPLOYEES</a>

    <a href="/sales">SALES</a>

    <a href="/customers">CUSTOMERS</a>

    <a href="/loans">LOANS</a>

    <a href="/users">USERS</a>

  </div>



  <!-- page title -->


  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <p id="title">Loans</p>
    </div>
    <div class="col-md-8">

    </div>
  </div>



  <!-- middle row page section -->




  <!-- form section -->
  <div class="row">

    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <div id="loancreatedform">

        <p id="formtitle">Loan Created</p>

        <p>
          <strong>Principal:</strong>
          <%= @loan.principal %>
        </p>

        <p>
          <strong>Interest rate:</strong>
          <%= @loan.interest_rate %>
        </p>

        <p>
          <strong>Periods:</strong>
          <%= @loan.periods %>
        </p>

        <p>
          <strong>Payment type:</strong>
          <%= @loan.payment_type %>
        </p>


        <% if can? :update, @loan %>
          <div id="backnlcreated">
            <%= link_to 'Back', loans_path,class:'btn btn-dark' %>
          </div>


          <div id="editnl">
            <%= link_to 'Edit', edit_loan_path(@loan),class:'btn btn-dark' %>
          </div>

        <%end%>


    </div>

    <div class="col-md-2">

    </div>

  </div>

<!--  Form Section Ends-->

  <!-- new grid row-->


  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <!-- add your code here -->
    </div>
    <div class="col-md-8">

    </div>
  </div>


  <%= render :partial => "loans/amortization_schedule"  %>

</div>

  <%=link_to "Create PDF document", loan_path(@loan, format: "pdf")%>







</div>