config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :loans
  resources :sales
  resources :employees
  resources :users
  resources :cars
  resources :customers
  root to: "cars#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord

  has_one_attached :image

  after_commit :add_default_image, on: [:create, :update]


  def self.search(search)
    if search
      where('color LIKE ? OR model LIKE ? OR year LIKE ? OR price LIKE ? OR vin LIKE ? OR maker LIKE ?',  "%#{search}%",  "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      all
    end
  end

  def add_default_image
    unless image.attached?
      self.image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'car-flat.png')),
                        filename: 'car-flat.png', content_type: 'image/png')
    end


  end


end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  #load_and_authorize_resource param_method: :my_sanitizer

 #  private
 # def my_sanitizer
 #   params.require(:car_params)
 # end
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all.paginate(:per_page => 25, :page => params[:page]).search(params[:search])
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    authorize! :create, @car
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    authorize! :update, @car
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    authorize! :destroy, @car
    @car = Car.find(params[:id])
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { render :layout => false}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:model, :color, :maker, :year, :price, :vin, :image)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :model %>
    <%= form.text_field :model, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :color %>
    <%= form.text_field :color, class: 'form-control' %>




  </div>

  <div class="field form-group">
    <%= form.label :maker %>
    <%= form.text_field :maker, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :year %>
    <%= form.number_field :year, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :vin %>
    <%= form.text_field :vin, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, class:'button' %>



      </div>


  <div class="actions" id="buttonright"  >

    <%= form.submit:class => 'btn btn-dark' %>
  </div>


<% end %>

app/views/cars/destroy.js.erb
$('.delete_car').bind('ajax:success', function() {
    $(this).closest('tr').fadeOut();
});

app/views/cars/edit.html.erb
<p id="notice"><%= notice %></p>



<div class="container-fluid">


  <!-- web application title -->
  <div class="col-xs-12 text-center">


    <p id="apptitle">Hou-Tex Auto Dealership</p>


  </div>



  <!--NEW navigation bar made using css instead of bootstrap-->


  <div class="topnav" id="myTopnav">

    <a href="/cars">CARS</a>

    <a href="/employees">EMPLOYEES</a>

    <a href="/sales">SALES</a>

    <a href="/customers">CUSTOMERS</a>

    <a href="/loans">LOANS</a>

    <a href="/users">USERS</a>

  </div>



  <!-- page title -->


  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <p id="title">Cars</p>
    </div>
    <div class="col-md-8">

    </div>
  </div>




  <!-- middle row page section -->
  <!-- form section -->
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">

      <div id="carform">
        <h1>Edit  Car</h1>


        <%= render 'form', car: @car %>



        <div id="backbutton">
          <%= link_to 'Show', @car,class: 'btn btn-dark' %>
           | <%= link_to 'Back', cars_path,class: 'btn btn-dark' %>

        </div>

      </div>






      </div>





    </div>
    <div class="col-md-2">

    </div>
  </div>


  <br>



</div>

app/views/cars/index.html.erb
<!-- CARS main page -->
<p id="notice"><%= notice %></p>



<div class="container-fluid">


  <!-- web application title -->
  <div class="col-xs-12 text-center">

    <div id="cartest"></div>
    <p id="apptitle">Hou-Tex Auto Dealership</p>


  </div>

  <!--NEW navigation bar made using css instead of bootstrap-->


  <div class="topnav" id="myTopnav">

    <a href="/cars" c>CARS</a>

    <a href="/employees">EMPLOYEES</a>


    <a href="/sales">SALES</a>


    <a href="/customers">CUSTOMERS</a>

    <a href="/loans">LOANS</a>

    <a href="/users">USERS</a>

  </div>



<!-- page title -->


<div class="row">
  <div class="col-md-2">

  </div>
  <div class="col-md-8">
    <p id="title">Cars</p>
  </div>
  <div class="col-md-8">

  </div>
</div>

<!-- car button and search bar -->

<div class="row">
  <div class="col-md-2">

  </div>
  <div class="col-md-8">
    <div id="rightsearch">

    <%= form_tag cars_path, :method => 'get', :id => "cars_search" do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil ,class: 'btn btn-dark'%>
      </p>
    <% end %>


    </div>
    <div id="leftcar">

      <% if can? :create, @car %>
        <%= link_to 'New Car', new_car_path,class: 'btn btn-dark' %>
      <%end%>
    </div>
  </div>
  <div class="col-md-2">

  </div>
</div>


<!-- table -->

<div class="row">
  <div class="col-md-2">

  </div>
  <div class="col-md-8">

    <table class="table table-bordered table-hover table-dark" id="cartable" >
      <thead>
      <tr>
        <th scope="col"  width="230px" >Model</th>
        <th scope="col"  width="230px" >Color</th>
        <th scope="col"  width="230px" >Maker</th>
        <th scope="col"  width="230px">Year</th>
        <th scope="col"  width="230px">Price</th>
        <th scope="col"  width="230px" >VIN</th>
        <th scope="col"  width="230px" >Image</th>
        <th colspan="3">Update</th>
      </tr>
      </thead>

      <tbody>
      <% @cars.each do |car| %>
        <tr>
          <th scope="row"><%= car.model %></th>
          <td><%= car.color %></td>
          <td><%= car.maker %></td>
          <td><%= car.year %></td>
          <td><%= car.price %></td>
          <td><%= car.vin %></td>
          <td><%=image_tag(car.image, style:'width:85px;height:40px') %></td>
          <td><%= link_to 'Show', car %></td>
          <td><%= link_to 'Edit', edit_car_path(car) %></td>
          <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' },
                          :remote => true, :class => 'delete_car'%></td>
        </tr>
      <% end %>
      </tbody>


    </table>


  </div>
  <div class="col-md-2">

  </div>
</div>





  <%= will_paginate @cars %>

<br>



</div>

app/views/cars/new.html.erb
<p id="notice"><%= notice %></p>



<div class="container-fluid">


  <!-- web application title -->
  <div class="col-xs-12 text-center">

    <div id="cartest"></div>
    <p id="apptitle">Hou-Tex Auto Dealership</p>


  </div>



  <!--NEW navigation bar made using css instead of bootstrap-->


  <div class="topnav" id="myTopnav">

    <a href="/cars" c>CARS</a>

    <a href="/employees">EMPLOYEES</a>

    <a href="/sales">SALES</a>

    <a href="/customers">CUSTOMERS</a>

    <a href="/loans">LOANS</a>

    <a href="/users">USERS</a>

  </div>



  <!-- page title -->


  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <p id="title">Cars</p>
    </div>
    <div class="col-md-8">

    </div>
  </div>




  <!-- middle row page section -->
  <!-- form section -->
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <div id="carform">

        <p id="formtitle">New Car</p>


        <%= render 'form', car: @car  %>

        <div id="backbutton">

          <%= link_to 'Back', cars_path,class: 'btn btn-dark' %>
        </div>

      </div>


    </div>
    <div class="col-md-2">

    </div>
  </div>







  <br>



</div>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>



<div class="container-fluid">


  <!-- web application title -->
  <div class="col-xs-12 text-center">

    <div id="cartest"></div>
    <p id="apptitle">Hou-Tex Auto Dealership</p>


  </div>



  <!--NEW navigation bar made using css instead of bootstrap-->


  <div class="topnav" id="myTopnav">

    <a href="/cars" c>CARS</a>

    <a href="/employees">EMPLOYEES</a>

    <a href="/sales">SALES</a>

    <a href="/customers">CUSTOMERS</a>

    <a href="/loans">LOANS</a>

    <a href="/users">USERS</a>

  </div>



  <!-- page title -->


  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <p id="title">Cars</p>
    </div>
    <div class="col-md-8">

    </div>
  </div>




  <!-- middle row page section -->
  <!-- form section -->
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">



      <div id="carform">
        <p id="formtitle">New Car Created</p>

        <p>
          <strong>Model:</strong>
          <%= @car.model %>
          <br/>

        </p>

        <p>
          <strong>Color:</strong>
          <%= @car.color %>
          <br/>

        </p>

        <p>
          <strong>Maker:</strong>
          <%= @car.maker %>
          <br/>

        </p>

        <p>
          <strong>Year:</strong>
          <%= @car.year %>
          <br/>

        </p>

        <p>
          <strong>Price:</strong>
          <%= @car.price %>
          <br/>

        </p>

        <p>
          <strong>Vin:</strong>
          <%= @car.vin %>
          <br/>

        </p>


        <p align="middle">

          <%=image_tag(@car.image, style:'width:462px;height:302px') %>

        </p>

        <% if can? :update, @car %>

          <div id="backnc">

            <%= link_to 'Back', cars_path ,class: 'btn btn-dark'%>
          </div>

          <div id="editnc">

            <%= link_to 'Edit', edit_car_path(@car),class: 'btn btn-dark' %>
          </div>

        <%end%>




      </div>





    </div>
    <div class="col-md-2">

    </div>
  </div>


  <br>



</div>