config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :loans
  resources :sales
  resources :employees
  resources :users
  resources :cars
  resources :customers
  root to: "cars#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord


  def car_total(car_price)

    markup = (0.082 * car_price) + car_price
    sales_tax = 0.043 * markup
    extraCosts = markup + sales_tax

    car_total = extraCosts
  end

  # def add (principal, interest_rate, periods, payment_type)
  #   puts  " values ---------"
  #   puts  principal
  #   puts interest_rate
  #   puts  "---------"
  #   @total = principal + periods + interest_rate + payment_type
  # end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /sales
  # GET /sales.json
  def index
    authorize! :index, @sale
    @sales = Sale.all
    #puts @sales
    respond_to do |format|
      format.html
      format.pdf do

        pdf = SalePdf.new(@sales)
        send_data pdf.render, filename: "Sales.pdf", type: "application/pdf",disposition: "inline"
        #wickedpdf
        #render pdf: "Sales.pdf", template: "sales_controller/index.html.erb" # layout: 'layouts/pdf.html.erb'



      end
      end

   end
  # GET /sales/1
  # GET /sales/1.json
  def show
    authorize! :show, @sale



      end


  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
    authorize! :edit, @sale
  end

  # POST /sales
  # POST /sales.json
  def create
    authorize! :create, @sale
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    authorize! :update, @sale
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    authorize! :destroy, @sale
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:salesperson, :salesperson_phone, :customer_name, :customer_lastname, :car_model, :car_make, :car_vin, :car_color, :car_price, :car_sales_tax, :car_markup, :car_total_price)
    end
  end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :salesperson %>
    <%= form.text_field :salesperson %>
  </div>

  <div class="field">
    <%= form.label :salesperson_phone %>
    <%= form.text_field :salesperson_phone %>
  </div>

  <div class="field">
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name %>
  </div>

  <div class="field">
    <%= form.label :customer_lastname %>
    <%= form.text_field :customer_lastname %>
  </div>

  <div class="field">
    <%= form.label :car_model %>
    <%= form.text_field :car_model %>
  </div>

  <div class="field">
    <%= form.label :car_make %>
    <%= form.text_field :car_make %>
  </div>

  <div class="field">
    <%= form.label :car_vin %>
    <%= form.text_field :car_vin %>
  </div>

  <div class="field">
    <%= form.label :car_color %>
    <%= form.text_field :car_color %>
  </div>

  <div class="field">
    <%= form.label :car_price %>
    <%= form.text_field :car_price %>
  </div>


  <div class="actions" id="buttonright">
    <%= form.submit:class => 'btn btn-dark' %>
  </div>

<% end %>

app/views/sales/edit.html.erb
<p id="notice"><%= notice %></p>



<div class="container-fluid">


  <!-- web application title -->
  <div class="col-xs-12 text-center">


    <p id="apptitle">Hou-Tex Auto Dealership</p>


  </div>



  <!--NEW navigation bar made using css instead of bootstrap-->


  <div class="topnav" id="myTopnav">

    <a href="/cars" c>CARS</a>

    <a href="/employees">EMPLOYEES</a>

    <a href="/sales">SALES</a>

    <a href="/customers">CUSTOMERS</a>

    <a href="/loans">LOANS</a>

    <a href="/users">USERS</a>

  </div>



  <!-- page title -->


  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <p id="title">Sales</p>
    </div>
    <div class="col-md-8">

    </div>
  </div>




  <!-- middle row page section -->
  <!-- form section -->
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">

      <div id="salesform">

        <p id="formtitle">Edit Sale</p>

        <%= render 'form', sale: @sale %>

        <div id="backbutton">
          <%= link_to 'Show', @sale,class: 'btn btn-dark' %> |
          <%= link_to 'Back', sales_path,class: 'btn btn-dark' %>
        </div>

      </div>





    </div>





  </div>
  <div class="col-md-2">

  </div>
</div>


<br>



</div>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>


<div class="container-fluid">

  <!-- web application title -->
  <div class="col-xs-12 text-center">
    <p id="apptitle">Hou-Tex Auto Dealership</p>
  </div>
</div>

<!--NEW navigation bar made using css instead of bootstrap-->


<div class="topnav" id="myTopnav">

  <a href="/cars" c>CARS</a>

  <a href="/employees">EMPLOYEES</a>

  <a href="/sales">SALES</a>

  <a href="/customers">CUSTOMERS</a>

  <a href="/loans">LOANS</a>

  <a href="/users">USERS</a>

</div>



<!-- page title -->


<div class="row">
  <div class="col-md-2">

  </div>
  <div class="col-md-8">
    <p id="title">Sales</p>
  </div>
  <div class="col-md-2">

  </div>
</div>






<!-- area above table -->
<div class="row">
  <div class="col-md-2">

  </div>
  <div class="col-md-8">

    <div id="createemp">



      <% if can? :create, @sale %>
        <%= link_to 'New Sale', new_sale_path,class: 'btn btn-dark'%>


      <%end%>


    </div>

    <div id="searchemp">
      <%= form_tag sales_path, :method => 'get', :id => "sales_search" do %>

        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil , class: 'btn btn-dark'%>

      <% end %>
    </div>

  </div>
  <div class="col-md-2">

  </div>
</div>

<!-- table -->
<div class="row">
  <div class="col-md-2">

  </div>
  <div class="col-md-8">
    <table class="table table-bordered table-hover table-dark" id="cartable" >
      <thead>
      <tr>
        <th scope="col"  width="230px" >Salesperson</th>
        <th scope="col"  width="230px" >Salesperson Phone</th>
        <th scope="col"  width="230px" >Customer Name</th>
        <th scope="col"  width="230px" >Customer Lastname</th>
        <th scope="col"  width="230px" >Car Model</th>
        <th scope="col"  width="230px">Car Make</th>
        <th scope="col"  width="230px">Car Vin</th>
        <th scope="col"  width="230px">Car Color</th>
        <th scope="col"  width="230px">Car Price</th>
        <th scope="col"  width="230px">Car Total Price</th>


<!--        <th colspan="3">Update Record</th>-->
      </tr>
      </thead>

      <tbody>
      <% @sales.each do |sale| %>
        <tr>
          <td><%= sale.salesperson %></td>
          <td><%= sale.salesperson_phone %></td>
          <td><%= sale.customer_name %></td>
          <td><%= sale.customer_lastname %></td>
          <td><%= sale.car_model %></td>
          <td><%= sale.car_make %></td>
          <td><%= sale.car_vin %></td>
          <td><%= sale.car_color %></td>
          <td><%= sale.car_price %></td>
          <td><%= sale.car_total(sale.car_price) %></td>
          <td><%= link_to 'Show', sale %></td>
          <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
          <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        </tr>
      <% end %>
      </tbody>
    </table>

  </div>
  <div class="col-md-2">

  </div>
</div>


<br>


</div>

app/views/sales/new.html.erb
<p id="notice"><%= notice %></p>



<div class="container-fluid">


  <!-- web application title -->
  <div class="col-xs-12 text-center">


    <p id="apptitle">Hou-Tex Auto Dealership</p>


  </div>



  <!--NEW navigation bar made using css instead of bootstrap-->


  <div class="topnav" id="myTopnav">

    <a href="/cars" c>CARS</a>

    <a href="/employees">EMPLOYEES</a>

    <a href="/sales">SALES</a>

    <a href="/customers">CUSTOMERS</a>

    <a href="/loans">LOANS</a>

    <a href="/users">USERS</a>

  </div>



  <!-- page title -->


  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <p id="title">Sales</p>
    </div>
    <div class="col-md-8">

    </div>
  </div>




  <!-- middle row page section -->
  <!-- form section -->
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">

      <div id="salesform">
        <p id="formtitle">New Sale</p>

        <%= render 'form', sale: @sale %>
        <div id="backbutton">
          <%= link_to 'Back', sales_path,class: 'btn btn-dark' %>
        </div>

      </div>





    </div>





  </div>
  <div class="col-md-2">

  </div>
</div>


<br>



</div>

app/views/sales/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "application" -%>
</head>
<body>
<div class='container'>
  <%= yield %>
</div>
</body>
</html>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>




<div class="container-fluid">


  <!-- web application title -->
  <div class="col-xs-12 text-center">


    <p id="apptitle">Hou-Tex Auto Dealership</p>


  </div>



  <!--NEW navigation bar made using css instead of bootstrap-->


  <div class="topnav" id="myTopnav">

    <a href="/cars" c>CARS</a>

    <a href="/employees">EMPLOYEES</a>

    <a href="/sales">SALES</a>

    <a href="/customers">CUSTOMERS</a>

    <a href="/loans">LOANS</a>

    <a href="/users">USERS</a>

  </div>



  <!-- page title -->


  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <p id="title">Sales</p>
    </div>
    <div class="col-md-8">

    </div>
  </div>




  <!-- middle row page section -->
  <!-- form section -->
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">

      <div id="salesform">
        <p id="formtitle">Sale Created</p>
        <p>
          <strong>Salesperson:</strong>
          <%= @sale.salesperson %>
        </p>

        <p>
          <strong>Salesperson phone:</strong>
          <%= @sale.salesperson_phone %>
        </p>

        <p>
          <strong>Customer name:</strong>
          <%= @sale.customer_name %>
        </p>

        <p>
          <strong>Customer lastname:</strong>
          <%= @sale.customer_lastname %>
        </p>

        <p>
          <strong>Car model:</strong>
          <%= @sale.car_model %>
        </p>

        <p>
          <strong>Car make:</strong>
          <%= @sale.car_make %>
        </p>

        <p>
          <strong>Car vin:</strong>
          <%= @sale.car_vin %>
        </p>

        <p>
          <strong>Car color:</strong>
          <%= @sale.car_color %>
        </p>

        <p>
          <strong>Car price:</strong>
          <%= @sale.car_price %>
        </p>

        <div id="backnc">

          <%= link_to 'Back', sales_path ,class: 'btn btn-dark' %>
        </div>

        <div id="editnc">
          <%= link_to 'Edit', edit_sale_path(@sale),class: 'btn btn-dark'  %>
        </div>







      </div>





  </div>
  <div class="col-md-2">

  </div>
</div>


<br>


  <%=link_to "Create PDF document", sales_path(@sale, format: "pdf")%>
</div>